### ISSUE TITLE
MacOS 13.4 M1 fails instalation

### ISSUE THREAD

**Issue by gamafreire** [kapteyn-astro/kapteyn#4]
Python 3.11.1 (main, Feb 19 2023, 11:58:30) [Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin

src/ascarray.c:3168:12: fatal error: 'longintrepr.h' file not found
#include "longintrepr.h"
^~~~~~~~~~~~~~~
5 warnings and 5 errors generated.
clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk build/temp.macosx-13-arm64-cpython-311/src/eterms.o build/temp.macosx-13-arm64-cpython-311/src/wcs.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/cel.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/flexed/wcsulex.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/flexed/wcsutrn.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/lin.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/log.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/prj.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/spc.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/sph.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/spx.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/tab.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcs.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcserr.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcsfix.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcshdr.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcsprintf.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcstrig.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcsunits.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcsutil.o build/temp.macosx-13-arm64-cpython-311/src/xyz.o -o build/lib.macosx-13-arm64-cpython-311/kapteyn/wcs.cpython-311-darwin.so
building 'ascarray' extension
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/lib/python3.11/site-packages/numpy/core/include -Isrc -Isrc/wcslib-4.24/C/ -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/ascarray.c -o build/temp.macosx-13-arm64-cpython-311/src/ascarray.o

I hope you can have time to see what's going on, since I really like Kapteyn

**Comment by gamafreire** [comment]
Python 3.11.1 (main, Feb 19 2023, 11:58:30) [Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin


src/ascarray.c:3168:12: fatal error: 'longintrepr.h' file not found
  #include "longintrepr.h"
           ^~~~~~~~~~~~~~~
5 warnings and 5 errors generated.
clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk build/temp.macosx-13-arm64-cpython-311/src/eterms.o build/temp.macosx-13-arm64-cpython-311/src/wcs.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/cel.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/flexed/wcsulex.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/flexed/wcsutrn.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/lin.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/log.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/prj.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/spc.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/sph.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/spx.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/tab.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcs.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcserr.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcsfix.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcshdr.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcsprintf.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcstrig.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcsunits.o build/temp.macosx-13-arm64-cpython-311/src/wcslib-4.24/C/wcsutil.o build/temp.macosx-13-arm64-cpython-311/src/xyz.o -o build/lib.macosx-13-arm64-cpython-311/kapteyn/wcs.cpython-311-darwin.so
building 'ascarray' extension
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/lib/python3.11/site-packages/numpy/core/include -Isrc -Isrc/wcslib-4.24/C/ -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/ascarray.c -o build/temp.macosx-13-arm64-cpython-311/src/ascarray.o


I hope you can have time to see what's going on, since I really like Kapteyn

**Comment by astroliang** [comment]
I also met some problems which seem to relate Apple

Processing ./kapteyn-3.0.tar.gz
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      /opt/homebrew/lib/python3.11/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING: The directory '/Users/liang/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
      WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/SciPy-1.11.1-py3.11.egg-info due to invalid metadata entry 'name'
      WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/numpy-1.25.0-py3.11.egg-info due to invalid metadata entry 'name'
      /opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py:561: UserWarning: The version specified ('Apple') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
        warnings.warn(
      running egg_info
      /opt/homebrew/lib/python3.11/site-packages/setuptools/_normalization.py:93: SetuptoolsDeprecationWarning: Invalid version: 'Apple'.
              !!
      
      
              ###################
              # Invalid version #
              ###################
              'Apple' is not valid according to PEP 440.
      
              Please make sure specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.
      
      
      !!
      
        warnings.warn(cleandoc(msg), SetuptoolsDeprecationWarning)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-req-build-xd4l8aqz/setup.py", line 216, in <module>
          setup(
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 220, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'Apple'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
